---
title: 'Class 6: R function'
author: "Gabrielle Blizard"
date: "4/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### About
This is my **class 6** R markdown document with my *code* and notes for the day.

```{r}
plot(1:10, typ="l", col="blue")
```

## Reading in files practice

There are 3 files to read.

```{r}
read.table("test1.txt", header = TRUE, sep = ",")
```


```{r}
read.table("test2.txt", header = TRUE, sep = "$")
```


```{r}
read.table("test3.txt", header = FALSE, sep = "")
```


```{r}
read.table("https://bioboot.github.io/bimm143_S19/class-material/test2.txt", header = TRUE, sep = "$")
```


## Functions

Our first silly function examples:

```{r}
add <- function(x, y=1) {
  # The body!!
  x + y
}
```

```{r}
add(10)
```

```{r}
add(10, 10)
```

```{r}
add( c(1, 2, 3) )
```

```{r}
add( c(1, 2, 3), 4)
```

```{r}
# add(1, 2, 3)
```


### Another example

```{r}
rescale <- function(x) {
   rng <-range(x, na.rm=TRUE)
   (x - rng[1]) / (rng[2] - rng[1])
}

```

```{r}
rescale(1:10)
```

```{r}
# How would you get your function to work here...
rescale( c(1,2,NA,3,10) )
```


```{r}
x <- c(1,2,NA,3,10) 
rng <- range(x, na.rm = TRUE)
#rng
(x - rng[1]) / (rng[2] - rng[1])
```

```{r}
rescale2 <- function(x, na.rm = TRUE) {
  if(!is.numeric(x)) {
    stop("You need to give only numbers please")
  }
   rng <-range(x, na.rm=na.rm)
   (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale2( c(1,3,NA,10), na.rm = FALSE)
```

```{r}
# What should we do here?
#rescale2( c(1,10,"string") )
```


```{r}
x <- c(1,10,"string")

is.numeric(x)

#range(x, na.rm=TRUE)
#(x - rng[1]) / (rng[2] - rng[1])
```

```{r}
 rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
    rng <-range(x, na.rm=na.rm)
    print("Hello")
    
   answer <- (x - rng[1]) / (rng[2] - rng[1])
   
   print("is it me you are looking for?")
   
   if(plot) {
      plot(answer, typ="b", lwd=4)
     print("Please dont sing again...")
   }
   print("I can see it in ...")
   return(answer)
}
```

```{r}
rescale3( c(1,3,NA,10))
```

```{r}
rescale3( c(1,3,NA,10), plot=TRUE)
```

